{% set name = "drfp" %}
{% set version = "0.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/drfp-{{ version }}.tar.gz
  sha256: 0ec79404d9c4de82e3e745cb7eac7b1b8086b90346001edd2dd6eaf0bb833198

build:
  number: 0
  noarch: python
  entry_points:
    - drfp = drfp.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=8.0.1
    - importlib_metadata
    - numpy >=1.21.0
    - python >=3.7
    - rdkit

test:
  imports:
    - drfp
  commands:
    - pip check
    - drfp --help
  requires:
    - pip

about:
  home: https://github.com/reymond-group/drfp
  summary: An NLP-inspired chemical reaction fingerprint based on basic set arithmetic.
  dev_url: https://github.com/reymond-group/drfp
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
