{% set name = "drfp" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/drfp-{{ version }}.tar.gz
  sha256: ea4755ad989bbd31a62cc628a7ae1bacdf2bfef0dfde5c899cb4551917405640

build:
  number: 1
  noarch: python
  entry_points:
    - drfp = drfp.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click >=8.0.1
    - importlib_metadata
    - numpy >=1.21.0
    - python >={{ python_min }}
    - rdkit

test:
  imports:
    - drfp
  commands:
    - pip check
    - drfp --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/reymond-group/drfp
  summary: An NLP-inspired chemical reaction fingerprint based on basic set arithmetic.
  dev_url: https://github.com/reymond-group/drfp
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
